### ISSUE TITLE
library not found for -lDomobAdSDK

### ISSUE THREAD

**Issue by ghost** [shingwasix/DomobAd-iOS-SDK#1]
After pod install, DomobAdSDK is missing when process linking.
And .a file is in dictionary right there.

**Comment by shingwasix** [comment]
Thanks for your comment,I have fixed this bug.
Please use `pod update` to update it.

**Comment by ghost** [comment]
It is nice to fix this issue quickly. But It still missing the  Domob when process linking in my computer.
Which version of pods are you using?
In my final result, it goes like this "LIBRARY_SEARCH_PATHS = $(PODS_ROOT)/#{s.name}"
It seems not ok.

**Comment by shingwasix** [comment]
Sorry,I have submited a wrong version`[4.4.8a]` to Spec.git.
I'm submitting a new version`[4.4.8-1]` now.
You could update it few minutes later.
